# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Kristian_Hristov

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository    
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies         
      run: npm ci  
    - name: Run username    
      run: echo Kristian_Hristov

  run-ui-tests:
        needs: build
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout the repository    
          uses: actions/checkout@v4
        - name: Use Node.js 20.x
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: 'npm'
        - name: Install npm dependencies         
          run: npm ci  
        - name: Install playwright browsers         
          run: npx playwright install  
        - name: Start the application         
          run: npm start &    
        - name: Run UI tests        
          run: npm run test:ui   

  deploy-production:
            needs: run-ui-tests
            runs-on: ubuntu-latest
            steps:
              - name: Deploy to production
                uses: johnbeynon/render-deploy-action@v0.0.8
                with:
                  service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
                  api-key: ${{ secrets.RENDER_API_KEY }}
                  wait-for-success: true          